### ISSUE TITLE
querySelectorAll not working

### ISSUE THREAD

**Issue by Dan9boi** [imgix/luminous#13]
Hi, just wanna say great plugin!

But what is the deal with having multiple elements, like a gallery, which all have to use Luminous. Then you'd have to create a loop for getting all elements with the same class, like this:

```javascript`
var triggers = document.querySelectorAll('.product-zoom');
[].forEach.call(triggers, function(trigger) {
    new Luminous(trigger);
});
```
This just seems like a lot of instances, wouldn't it be better to support the NodeList, returned by  document.querySelectorAll out of the box?

Or am I missing something?

**Comment by paulstraw** [comment]
Hey @Dan9boi, thanks for reaching out. Luminous follows the common vanilla JS library pattern of accepting a single DOM element for initialization. For a good example, check out David Desandro's venerable [Masonry](http://masonry.desandro.com/#getting-started) (under "Initialize with Vanilla JavaScript").

There's definitely not a concern about having too many instances; basically any jQuery plugin that accepts multiple elements as input does a similar thing internally (See the [Masonry jQuery bridge](https://github.com/desandro/masonry/blob/master/dist/masonry.pkgd.js#L117) for a good example of that). Basically at some point, something has to iterate over the list and create instances.

That being said, it's on my list to eventually include a wrapper that works with the common DOM libs like jQuery and Zepto to provide `$('.product-zoom').luminous({opt: 'val'})` style functionality.

Hopefully that answers your question. Let me know if I can help clarify anything!

**Comment by Dan9boi** [comment]
Ok, thank you for the clarification :)
