### ISSUE TITLE
Only working on the first image

### ISSUE THREAD

**Issue by mtsweir** [imgix/luminous#14]
Downloaded the manual version of this and duplicated the demo link a number of times, but it only opens the first image in a lightbox, the rest only open as a default click to the image.

**Comment by paulstraw** [comment]
Hey @mtsweir, can you send through the code you're using?

**Comment by mtsweir** [comment]
My header css looks like this:
`<link rel="stylesheet" href="css/style.css">
  <link rel="stylesheet" media="screen, projection" href="node_modules/luminous-lightbox/dist/luminous-basic.css">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>`

Demo content looks like this:
`<div class="col-sm-6 col-md-4 image-block-tile">
          <a class="lightbox" href="src/img/website.jpg"><img class="img-fluid" src="src/img/website-thumb.jpg" alt=""></a>
        </div>`

My footer scripts look like this:
`<div class="scripts">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<script src="src/js/bootstrap.min.js"></script>
  <script src="node_modules/luminous-lightbox/dist/Luminous.min.js"></script>
  <script>
    $(function () {
      new Luminous(document.querySelector('a.lightbox'));
    });
  </script>
</div>`

**Comment by paulstraw** [comment]
`document.querySelector` only returns the first matching element. What you'd typically want to do in this case is use `document.querySelectorAll` and a loop, but since you've got jQuery loaded anyway, we can use that:

``` javascript
$(function() {
  $('a.lightbox').each(function(i, el) {
    new Luminous(el);
  });
});
```

Hope that helps, let me know if you have any other questions!

**Comment by mtsweir** [comment]
Beautiful, thank you sir!

**Comment by paulstraw** [comment]
:+1:
