### ISSUE TITLE
requiring ./util/

### ISSUE THREAD

**Issue by Haroenv** [imgix/luminous#15]
For some reason, it seems to require `./util`, and if it doesn't, it throws an error

```js
      throw er; // Unhandled 'error' event
      ^
Error: module "./util/dom" not found from "/node_modules/luminous-lightbox/dist/Luminous.js"
```

This is returned when I try to do

```js
var Luminous = require('luminous-lightbox');
```

or 

```js
require('luminous-lightbox');
```

I'm making use of Browserify

**Comment by paulstraw** [comment]
Hey @Haroenv, I'm going to make some changes to how Luminous is set up in order to work better with more JS environments. I'll update you as soon as that's taken care of.

**Comment by Haroenv** [comment]
Okay, thanks for your consideration

**Comment by paulstraw** [comment]
Hey @Haroenv, can you give this a go with 0.2.4 and let me know if you're still running into any issues? It should be set now.

**Comment by Haroenv** [comment]
I will tomorrow

**Comment by Haroenv** [comment]
I've updated to 0.2.4, but I still get this: 


```js
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: module "./util/dom" not found from "/Users/haroenv/git/cws2_labo_01_viaene_haroen/node_modules/luminous-lightbox/dist/Luminous.js"
    at notFound (/Users/haroenv/git/cws2_labo_01_viaene_haroen/node_modules/browserify/index.js:803:15)
    at /Users/haroenv/git/cws2_labo_01_viaene_haroen/node_modules/browserify/index.js:754:23
    at /Users/haroenv/git/cws2_labo_01_viaene_haroen/node_modules/browser-resolve/index.js:185:24
    at /Users/haroenv/git/cws2_labo_01_viaene_haroen/node_modules/browser-resolve/node_modules/resolve/lib/async.js:36:22
    at load (/Users/haroenv/git/cws2_labo_01_viaene_haroen/node_modules/browser-resolve/node_modules/resolve/lib/async.js:54:43)
    at /Users/haroenv/git/cws2_labo_01_viaene_haroen/node_modules/browser-resolve/node_modules/resolve/lib/async.js:60:22
    at /Users/haroenv/git/cws2_labo_01_viaene_haroen/node_modules/browser-resolve/node_modules/resolve/lib/async.js:16:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by paulstraw** [comment]
Hmm, I can't replicate this with `0.2.4`. Could you send through a minimum test case?

**Comment by Haroenv** [comment]
Can you reproduce with this: https://github.com/Haroenv/luminous-test ?

**Comment by paulstraw** [comment]
Ah, I see what's going on, thanks for the great example. This is happening because Browserify is effectively trying to re-Browserify a file that has already been Browserified (all Luminous' requirements have already been inlined in the UMD style in the dist file referenced). Since this is the case, you can work around it by adding the Browserify `noParse` option to your config, e.g.:

```
// … more code up here
.pipe(browserify({
  insertGlobals : true,
  noParse: ['luminous-lightbox']
}))
```

Let me know if that does the trick for your use case!

**Comment by paulstraw** [comment]
Hey @Haroenv, I'm going to go ahead and close this, but please feel free to reopen if the above update doesn't solve the issue for you!

**Comment by Haroenv** [comment]
I'm not able to test that RN, but if it does, wouldn't it be useful to put it in the README?

**Comment by paulstraw** [comment]
Sure thing. I'll reopen for that.

**Comment by paulstraw** [comment]
Added a note about this in fb9130c3c9adbad9e6eb530ddaa59a3f29a79f0a
