### ISSUE TITLE
TypeScript typings file

### ISSUE THREAD

**Issue by sylveon** [imgix/luminous#177]
**Before you submit:**

- [x] Please search through the existing issues (both open AND closed) to see if your feature has already been discussed. Github issue search can be used for this: https://github.com/imgix/luminous/issues?utf8=%E2%9C%93&q=is%3Aissue
- [x] Please take a moment to find out whether your idea fits with the scope and aims of the project

**Is your feature request related to a problem? Please describe.**
TypeScript is a language by Microsoft that has strict type checking which transpiles to JS. Currently using LuminousGallery with it requires to use the `any` type, which defeats type checking.

**Describe the solution you'd like**
LuminousGallery on npm should ship with a .d.ts file (declared in the package.json as the `types` field) which will allow TypeScript to provide type checking even for native JS modules.

**Comment by jayeb** [comment]
Hi @sylveon,

Thanks for the ticket. Given Typescript's growing place in the front-end world I agree that this would be an improvement for this library. However, looking at our current roadmap I think it's unlikely that we'll get to this anytime soon.

If you're jazzed up for this though, I'd encourage you to open a PR with the necessary configuration updates!
