### ISSUE TITLE
Image doesn't resize properly in Firefox (45.0.2)

### ISSUE THREAD

**Issue by bertramakers** [imgix/luminous#19]
I noticed that images opened in Luminous don't resize properly in Firefox (45.0.2). This behavior is even noticeable on the Luminous demo page: http://imgix.github.io/luminous/

Simply open the image and play with the window size. Particularly resizing the width is troublesome for the demo image (because it's in landscape).

I've been looking around the element inspector what could fix this, and I think it can be fixed by simply setting a max-width and max-height on the .lum-lightbox-image-wrapper

The max-width and max-height should be the same as the width and height that are dynamically calculated for that same element.

If I'm not mistaken this could be set here: https://github.com/imgix/luminous/blob/master/src/js/Lightbox.js#L82-L86

This solves the issue in Firefox, and doesn't seem to create any side effects in Chrome. I haven't been able to test this in IE/Edge.

**Comment by bertramakers** [comment]
I went ahead and created a pull request, but it seems the new build made some changes to the encapsulation of some function. I followed the instructions from https://github.com/imgix/luminous/blob/master/CONTRIBUTING.md, so I'm not sure if I missed something. I committed the new dist files separately so they can easily be reverted and build again if necessary.

**Comment by paulstraw** [comment]
Odd. I'm going to manually rebuild and merge that in. I'd be interested to know why you're getting different build output, I may need to lock some things down a bit more in package.json. Can you send through the output of a `npm list` from your Luminous working dir?

Either way, thanks for the PR! I'll have a new version out with this fix shortly.

**Comment by paulstraw** [comment]
Just released 0.2.5! https://github.com/imgix/luminous/releases/tag/0.2.5

**Comment by bertramakers** [comment]
Thanks for the fast reply and for merging my PR!
I've attached the output from npm list below.
[npm-list.txt](https://github.com/imgix/luminous/files/231386/npm-list.txt)

**Comment by paulstraw** [comment]
I'm not totally sure what's going on there, but it seems like one of the deps just slightly changed how they output JS with an update. I `rm -r`'d my `node_modules` and `npm install`ed, and now my output matches yours. Everything seems fine though, and the changes are fine by me, so I just went ahead and committed them. Thanks again for the PR, and for sending through your `npm list`!
