### ISSUE TITLE
CSS problem in ASP.NET Web application & Angular

### ISSUE THREAD

**Issue by stavBodik** [imgix/luminous#216]
Please Add to the usage instructions that users must include this in the styles.css file :

@import "~luminous-lightbox/dist/luminous-basic.css";

**Comment by sherwinski** [comment]
Hi @stavBodik, apologies for the super-delayed response to this issue. Just to be clear on usage specifics: the `lumunous-basic` stylesheet is not _required_ to use this package but is provided for users that don't want to worry about figuring out the CSS themselves. As per the [theming section](https://github.com/imgix/luminous#theming) in this repo's README:

>There is an included basic theme that may meet your needs, or at least give a good example of how to build out your own custom styles.

Users can obviously choose to extend this theme or refuse to use it altogether. Although I do admit that we could be more descriptive here by actually pointing to `lumunous-basic.css`, so we'll look to add that in documentation.
