### ISSUE TITLE
Image gallery

### ISSUE THREAD

**Issue by tompazourek** [imgix/luminous#24]
Hi Paul,

Thanks for a great library.

I was wondering if there are any guidelines or recommendations on how to display a set of images with some navigation. I know that many lightboxes often have some support for these use cases, I was wondering if there's some way of extending luminous to do that or if there are any future plans for that feature.

**Comment by paulstraw** [comment]
Luminous doesn't currently have image gallery support, but I'm certainly not opposed to adding it. I'm not quite sure offhand yet when I'll be able to fit this in. If you wanted to take a stab at it, I'd also happily look at a PR. Feel free to bounce ideas off me here!

**Comment by alexv9** [comment]
Hi Paul, I would also be very interested in this feature 👍 
Simple next, prev. buttons to flip through all images with the luminous class would be great.

**Comment by paulstraw** [comment]
Hey @tompazourek  and @alexv9. I've just added this in [0.3.0](https://github.com/imgix/luminous/releases/tag/0.3.0) with the new LuminousGallery class. It should be documented pretty well in the readme, but let me know if anything needs clarification!
