### ISSUE TITLE
caption not being updated when changing with prev/next

### ISSUE THREAD

**Issue by garygreen** [imgix/luminous#243]
When you use a function for `caption` and use the luminous gallery prev/next arrows, it won't call the `caption` function to update. If you close the lightbox and open it does update.

Probably best shown with a gif:

![2019-05-24_00-51-14](https://user-images.githubusercontent.com/1702638/58293691-76172f80-7dbe-11e9-8286-e350dc684441.gif)

https://codesandbox.io/embed/relaxed-mendel-j213i

**Comment by garygreen** [comment]
I think the problem is that I'm relying on `triggerEl` to work out what element triggered/is being opened in the lightbox but that doesn't appear to ever get updated, [`showNext` uses `currentTrigger`](https://github.com/imgix/luminous/blob/master/src/js/Lightbox.js#L301) - not sure how to access that exactly.

![image](https://user-images.githubusercontent.com/1702638/58294572-be385100-7dc2-11e9-9ff3-4e65bbcf5fc9.png)

**Comment by garygreen** [comment]
For now I've managed to find a way to get the `currentTrigger` but it seems a bit hacky, especially as `_gallery` looks to be private.

```js
new LuminousGallery(anchors, {}, {
    caption: function() {
        // Hack/workaround. See: https://github.com/imgix/luminous/issues/243
        var currentTriggerEl = this._gallery.luminousInstances[0].lightbox.currentTrigger;
        
        var position = anchors.indexOf(currentTriggerEl) + 1;

        return position + ' of ' + anchors.length;
    }
});
```

**Comment by sherwinski** [comment]
Hey @garygreen thanks for bringing this to our attention. As you pointed out, you won't be able to access the current trigger element via `triggerEl`. I think your workaround is sufficient but there could be a more intuitive way for other users who want to do the same thing. If you're willing, I'd be happy to review a PR that exposes the current trigger element on the `LuminousGallery` object with some accompanying tests.

**Comment by garygreen** [comment]
Hey thanks for the response. I decided to use another lightbox library so I don't think I'll get around to doing a PR so will close this issue for now

**Comment by billythekid** [comment]
I know this is a closed issue but the trigger element is passed to the function, which means you can access any attributes on that element. For me I found that simply supplying a `data-caption` attribute to the limunous link meant I could simply do something like:

```js
  new LuminousGallery(
    document.querySelectorAll(".luminous-link"),
    {
      arrowNavigation: true
    },
    {
      caption: function(trigger) {
        return trigger.dataset.caption;
      }
    }
  );
```

and use selectors something like this in the HTML:

```html
<a href="http://example.com/image.jpg" class="luminous-link" data-caption="My Caption"><img src="http://example.com/image-small.jpg" alt="My Alt Text"></a>
<a href="http://example.com/image2.jpg" class="luminous-link" data-caption="My Next Caption"><img src="http://example.com/image2-small.jpg" alt="My Next Alt Text"></a>
```

If I click the arrows in the gallery the caption is updated.
