### ISSUE TITLE
Lightbox isn't working in IE9 *FIX*

### ISSUE THREAD

**Issue by wolf-w** [imgix/luminous#28]
IE leaves you alone with the following message:
```
TypeError: Die Eigenschaft "add" eines undefinierten oder Nullverweises kann nicht abgerufen werden.
   {
      [functions]: ,
      description: "Die Eigenschaft "add" eines undefinierten oder Nullverweises kann nicht abgerufen werden.",
      message: "Die Eigenschaft "add" eines undefinierten oder Nullverweises kann nicht abgerufen werden.",
      name: "TypeError",
      number: -2146823281
   }
```
no line numbers, no filename, just nothing.

after a bit of exploring the Lightbox object i found usages of classList.
So, You need to **include a classList Polyfill** and the Lightbox will work too in IE >= 9

-i knew that support is only for the last 2 versions of every Browser, but i think it will stop some Developers to use this Lightbox, if they notice that IE9 isn't supported, so here is a fix for them c:

**Comment by paulstraw** [comment]
Hey @wolf-w, thanks for detailing this. Luminous currently guarantees compatibility with the following browsers: https://github.com/imgix/luminous#browser-support

As all of those browsers support `classList`, we won't be adding this polyfill functionality at this point. You are, of course, welcome to include the polyfill in your page. If you do that, Luminous _may_ work in IE 9 and friends, but there could also be other issues, as it is untested and unsupported. If it does work, that is also not a guarantee that it will continue to work in future releases of Luminous.

Let me know if you have any questions!

**Comment by wolf-w** [comment]
Hi,
i know That you wan't add it to the core, but u can write it down to the docs, so other developers can find a fix easily

**Comment by paulstraw** [comment]
Since it's officially unsupported (and other issues may be present in browsers that don't support `classList`), we won't be documenting this at this time.
