### ISSUE TITLE
`new Luminous` requires a DOM element as its first argument.

### ISSUE THREAD

**Issue by ZeldOcarina** [imgix/luminous#305]
Hello!

I'm trying to make Lightbox working but I get the quoted error.

This is my code:

index.js

`import { Luminous } from 'luminous-lightbox';

console.log(document.querySelectorAll('.gallery'));
new Luminous(document.querySelectorAll('.gallery'));`

immobile-show.ejs;
`<% if(immobile.immagini) { if(immobile.immagini.length > 0) { %><% immobile.immagini.forEach(function(immagine, i) { %>
                    <% if (i < 1) { return } %>
                    <% console.log(immagine) %>
                    <a class="gallery" href="<%= immagine %>" data-lightbox="immagini">
                        <img class="immobile-show__riga--img" src="<%= immagine %>" class="immagine-secondaria-show">
                    </a>
                <% })}}; %>`

Any suggestion?

**Comment by sherwinski** [comment]
Hi @ZeldOcarina,
`document.querySelectorAll()` returns a `Nodelist` but the Luminous constructor expects a single element. I would instead try:

```js
new Luminous(document.querySelectorAll('.gallery')[0]);
```

**Comment by sherwinski** [comment]
Hi @ZeldOcarina, I'm going to close this issue but feel free to comment back if you have any more questions. Thanks
