### ISSUE TITLE
Trigger close from within a caption?

### ISSUE THREAD

**Issue by cschults** [imgix/luminous#37]
Love the simplicity of Luminous. How might one set the closeTrigger option to fire off a click within the caption?

Use case: I have an image which is an excerpt of an infographic. I'd like the user to either click on the image or a link within the caption to go to another page with the full infographic. Thus, using "click" for closeTrigger won't work as clicking on the link would close the lightbox. Thus, I'd like to include a "close" link within the caption.

One possible feature idea is to add an option to include an "X" icon place upper-right to alternatively trigger a close.

**Comment by paulstraw** [comment]
Hey @cschults. There's actually a `close` method on Luminous instances, so you could set it up something like this (using jQuery for example simplicity):

``` javascript
var myLum = new Luminous(…);

$('body').on('click', '.lum-lightbox-caption', function() {
  myLum.close();
});
```

Let me know if that works for you! Feel free to reopen this issue if you have more questions/comments.

**Comment by cschults** [comment]
Thanks @paulstraw! I can get it to work, but subsequent attempts to reopen the lightbox results in the immediate closing of it. Will dig deeper, but if you have any suggestions, please do share!

**Comment by paulstraw** [comment]
That's interesting. Could you possibly put together a reduced test case on CodePen or similar?

**Comment by cschults** [comment]
@paulstraw I realized this behavior is caused when closeTrigger is set to "mouseleave", which I neglected to remove from a previous version. Working if set to "". Thanks for your help!

If you're interested in seeing the bug:
[http://codepen.io/anon/pen/RGmvqp](url)

**Comment by paulstraw** [comment]
Very cool, glad you got it sorted!

**Comment by jeremymouton** [comment]
I ran into a similar issue with `LuminousGallery`, where I needed to be able to click a link in the caption while keeping the lightbox open.

Unfortunately, there is no `.close()` for LuminousGallery.

Here's my workaround if anyone else is wondering – there is probably a cleaner way to do this, please let me know how I can improve it.


```js
import $ from 'jquery'
import { LuminousGallery } from 'luminous-lightbox'

// LuminousGallery options
const options = {
  arrowNavigation: true,
}

// Create gallery
let gallery = new LuminousGallery($('.js-gallery'), options, {
  caption: trigger => trigger.querySelector('img').getAttribute('data-caption'),
  closeTrigger: '', // disable closeTrigger
})

/**
 * Custom code starts here
 * 
 */
 
// Get all gallery triggers, and declare an Index
let triggers = $('.js-gallery'),
    triggerIndex;

// Find the index of the clicked gallery trigger
$('.js-gallery').on('click', function() {
  triggerIndex = triggers.index($(this));
})

// Prevent anchor in caption from closing the gallery
$('body').on('click', '.lum-lightbox-caption a', function(e) {
  e.stopPropagation()
})

// New close handler
$('body').on('click', '.lum-lightbox', function(e) {
  gallery.luminousInstances[triggerIndex].close()
});

```


Hope this helps someone!
