### ISSUE TITLE
Won't work using ajax

### ISSUE THREAD

**Issue by mikwehttam** [imgix/luminous#40]
I created simple gallery and used the plugin for the lightbox, I used ajax for the categories, but when the ajax loads the lightbox won't work anymore

**Comment by OZZlE** [comment]
1) Learn javascript 2) Call documented methods when ajax is complete..

**Comment by frederickfogerty** [comment]
Hey @mikwehttam 👋 

Fred from Imgix here - I'm responsible for maintaining this repo from today onwards. Sorry to hear that you couldn't get this to work! Is this still an issue? If it is, could you please add some example code or a way that I could reproduce your issues? Thanks! - Fred, Imgix

**Comment by frederickfogerty** [comment]
As this issue is stale, I'm going to close this. Please feel free to open another issue if this issue persists!
