### ISSUE TITLE
Image doesn't display on re-open in Safari and is stuck on loading

### ISSUE THREAD

**Issue by seanwash** [imgix/luminous#42]
Safari 10.0.3

## To reproduce

* Visit https://imgix.github.io/luminous/ in safari
* Click on image, then close it
* Click on image again

Here's a gif of the behavior, as well as the devtools showing the image is still in the DOM: https://cl.ly/jGo8

**Comment by rzecchini** [comment]
Same here. Safari 9.1.2.
I think it is due to a fail in removing the `lum-loading` class. 
Anyone solved it?

**Comment by frederickfogerty** [comment]
Hey @seanwash and @rzecchini 👋 

Fred here from Imgix. I'll be responsible for maintaining this library from today onwards. It seems that this is related to #49. I'll have a look and see if I can reproduce this week.

**Comment by frederickfogerty** [comment]
Hey @seanwash I've had a look at this and have tried to reproduce. I can't reproduce this on my version of Safari `11.1 (13605.1.33.1.2)`. 

I searched around as to how to install an older version of Safari, but it seems to be [incredibly difficult](https://stackoverflow.com/questions/33423269/is-there-a-way-to-install-emulate-an-older-version-of-safari-i-e-8). I'm going to mark this as closed, but please comment if you're still having this issue and we can work out a way to solve it.
