### ISSUE TITLE
Lightbox image not centred in mobile safari

### ISSUE THREAD

**Issue by spnkr** [imgix/luminous#44]
![image](https://user-images.githubusercontent.com/11250/27513799-3b9fdc14-5942-11e7-99d8-43ca1e33ee4b.png)

**Comment by frederickfogerty** [comment]
Hey @spnkr 👋 

Fred from Imgix here. I'm responsible for maintaining this repo from today onwards. Can you confirm if this is still an issue? I'll try have a look at this later this week anyway.
