### ISSUE TITLE
injectBaseStyles not setting

### ISSUE THREAD

**Issue by ivanff** [imgix/luminous#478]
var injectBaseStyles = options["injectBaseStyles"] || true; // Internal use only!

if set to false, it always true

**Comment by sherwinski** [comment]
Hi @ivanff 👋, thanks for bringing this to our attention. Agreed that this should be fixed, I'll set some time apart in the next week to address it.

**Comment by sherwinski** [comment]
Hi @ivanff 👋, thanks for bringing this to our attention. Agreed that this should be fixed, I'll set some time apart in the next week to address it.

**Comment by sherwinski** [comment]
Hi @ivanff, the fix for this issue is now released in [v2.3.3](https://www.npmjs.com/package/luminous-lightbox) 🎉
