### ISSUE TITLE
I want to give a class name to the enlarged image.

### ISSUE THREAD

**Issue by asako08** [imgix/luminous#518]
Is it possible to give a specific class name to a specific enlarged image?

**Comment by frederickfogerty** [comment]
Hi there @asako08 👋  thanks for the question. 

At this stage, there's no way to do this specifically, but a workaround is to use the default enlarged image class `.lum-open`, or pass a `namespace` property when creating the Luminous instance, which will then cause the lightbox to have a class of `.{namespace}-open`, when enlarged.

```
new Luminous(document.querySelector("a"), { 
  namespace: 'my-custom-namespace' 
});
```

[Documented here](https://github.com/imgix/luminous#options--defaults).

Thanks!

**Comment by asako08** [comment]
Thank you very much.
Solved!
