### ISSUE TITLE
Include license in distributed JS

### ISSUE THREAD

**Issue by jdoubleu** [imgix/luminous#552]
It would be nice, if you could include a license (e.g. as a JavaScript comment) in the [distributed js file(s)](https://github.com/imgix/luminous/blob/main/dist/Luminous.min.js).

According to your license, I have to include the copyright notice. However, if I'm just including the minified bundle, I have to display the copyright notice somewhere else. So if its included within your dist, it would make things easier for me.

Take the [`bootstrap.min.css`](https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap.min.css)  bundle/dist as an example.

**Comment by sherwinski** [comment]
Hey there @jdoubleu and thanks for opening this request. Our team will discuss this question during our next sync-up and get back to you soon after.

**Comment by sherwinski** [comment]
Hey @jdoubleu,

After discussing with the team, this sounds like something we can patch in easily. I'll update you once a PR is out.

**Comment by sherwinski** [comment]
Hey @jdoubleu, the latest release ([v2.3.4](https://github.com/imgix/luminous/releases/tag/v2.3.4)) should include the copyright notice 🎉
