### ISSUE TITLE
closetrigger?

### ISSUE THREAD

**Issue by Nikodemsky** [imgix/luminous#564]
So basically i'm trying to disable close trigger on click, but no matter what i put in closeTrigger variable it still closing with the click.

Any help would be much appreciated.

**Comment by frederickfogerty** [comment]
Hi @Nikodemsky, thanks for the PR 👋  Would you be able to create a reproducible example for us with a codesandbox/codepen or similar? Then we can take a look at this properly 🙌

**Comment by frederickfogerty** [comment]
I'm closing this due to a lack of activity. If there is an update, please comment and we can re-investigate this issue.
