### ISSUE TITLE
Add full (correct) testsuite, including dist files

### ISSUE THREAD

**Issue by DanielRuf** [imgix/luminous#59]
We need a full testsuite. Currently what we have in `test` is not sufficient and does not use the files from `dist`.

Let me know how we can help here.

**Comment by frederickfogerty** [comment]
Hey there Daniel,

I'm from Imgix and starting from today I'll be responsible for maintaining this repo (along with all the other Imgix JS repositories) in the future. Testing is high on our priority list, so I'd like to see how we could collaborate on developing a decent test suite for luminous. 

You can help here by:
- outlining any issues with the testing at a high level (you've already mentioned that there are no tests which use `dist`)
- outline any specific scenarios or configurations that aren't tested
- outline any specific tests that you would like added.

Then, we can discuss what the best way to move forward is. We are committed to ensuring the proper testing of this library in the future.

- Fred, Imgix

**Comment by frederickfogerty** [comment]
Hey @DanielRuf, just checking in again to see if you had any ideas on how we could improve the tests for this library. Thanks!
